// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.kgromov.model;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kgromov.model.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country = 1;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 1;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string zip_code = 3;</code>
   * @return The zipCode.
   */
  java.lang.String getZipCode();
  /**
   * <code>string zip_code = 3;</code>
   * @return The bytes for zipCode.
   */
  com.google.protobuf.ByteString
      getZipCodeBytes();

  /**
   * <code>string street = 4;</code>
   * @return The street.
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 4;</code>
   * @return The bytes for street.
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>string alternative_address = 5;</code>
   * @return The alternativeAddress.
   */
  java.lang.String getAlternativeAddress();
  /**
   * <code>string alternative_address = 5;</code>
   * @return The bytes for alternativeAddress.
   */
  com.google.protobuf.ByteString
      getAlternativeAddressBytes();
}
