// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.kgromov.model;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kgromov.model.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>.com.kgromov.model.Gender gender = 4;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.com.kgromov.model.Gender gender = 4;</code>
   * @return The gender.
   */
  com.kgromov.model.Gender getGender();

  /**
   * <code>.com.kgromov.model.Address address = 5;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.com.kgromov.model.Address address = 5;</code>
   * @return The address.
   */
  com.kgromov.model.Address getAddress();
  /**
   * <code>.com.kgromov.model.Address address = 5;</code>
   */
  com.kgromov.model.AddressOrBuilder getAddressOrBuilder();
}
