// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.kgromov.model;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kgromov_model_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kgromov_model_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kgromov_model_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kgromov_model_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\021com.kgromov.model\"\223\001\n\006Pe" +
      "rson\022\n\n\002id\030\001 \001(\005\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\t" +
      "last_name\030\003 \001(\t\022)\n\006gender\030\004 \001(\0162\031.com.kg" +
      "romov.model.Gender\022+\n\007address\030\005 \001(\0132\032.co" +
      "m.kgromov.model.Address\"g\n\007Address\022\017\n\007co" +
      "untry\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\020\n\010zip_code\030\003 " +
      "\001(\t\022\016\n\006street\030\004 \001(\t\022\033\n\023alternative_addre" +
      "ss\030\005 \001(\t*8\n\006Gender\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001" +
      "\022\030\n\013TRANSGENDER\020\377\377\377\377\377\377\377\377\377\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kgromov_model_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kgromov_model_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kgromov_model_Person_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Gender", "Address", });
    internal_static_com_kgromov_model_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kgromov_model_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kgromov_model_Address_descriptor,
        new java.lang.String[] { "Country", "City", "ZipCode", "Street", "AlternativeAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
